In [87]:
# pandas>> it is an open source , BCD licensed library with high performance and easy to use in data structure and used for data analysis in python

In [ ]:
# Data frame>> the data is converted data frame it is an combo of rows&columns it is represented as same as the excel sheet looks

In [6]:
import pandas as pd 
import numpy as np
df= pd.DataFrame(np.arange(0,20).reshape(5,4),index=["R1","R2","R3","R4","R5"],columns=["C1","C2","C3","C4"])

In [7]:
df.head()

    C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [9]:
df.to_csv("Table1.csv") # this will create an csv file type of excel

In [10]:
df.loc["R4"] # this will accessed the values of C1,C2,C3,C4 columns with respect to R4 columns

C1    12
C2    13
C3    14
C4    15
Name: R4, dtype: int64

In [4]:
import numpy as np 
import pandas as pd
df= pd.DataFrame(np.arange(0,20).reshape(5,4),index=["R1","R2","R3","R4","R5"],columns=["C1","C2","C3","C4"])
df.iloc[0:2,0:2] # here both rows and columns are accessed simultaneously with the help of iloc

    C1  C2  C3
R1   0   1   2
R2   4   5   6
R3   8   9  10

In [6]:
type(df.iloc[0:2,0:2])

pandas.core.frame.DataFrame

In [7]:
df.iloc[0:2,0]

R1    0
R2    4
Name: C1, dtype: int64

In [9]:
type(df.iloc[0:2,0])

pandas.core.series.Series

In [10]:
df.iloc[:,1:] # this removes the column C1 from the table taken the values of C1 out

    C2  C3  C4
R1   1   2   3
R2   5   6   7
R3   9  10  11
R4  13  14  15
R5  17  18  19

In [12]:
df.iloc[:,:].values # here the whole dataframe is converted into array using .values function

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
df.isnull().sum() #  to find the null values

C1    0
C2    0
C3    0
C4    0
dtype: int64

In [18]:
df['C1'].value_counts() # this prints the repeated values in the column 1

C1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [19]:
df['C1'].unique() # this gives the unique values of the column 1

array([ 0,  4,  8, 12, 16])

In [22]:
df['C1'] # to simply call any columns

R1     0
R2     4
R3     8
R4    12
R5    16
Name: C1, dtype: int64

In [23]:
type(df['C1']) # this is an Series type cause its acesses only the rows

pandas.core.series.Series

In [25]:
df = pd.read_csv("mercedesbenz.csv")
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB

In [27]:
df.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [30]:
test_df = pd.read_csv('Test1.csv',sep=';')
test_df.head()

  ,Column1,Column2,Column3,Column4
0                     Row1,0,1,2,3
1                     Row2,4,5,6,7
2                   Row3,8,9,10,11
3                 Row4,12,13,14,15
4                 Row5,16,17,18,19

In [31]:
df["X0"].value_counts()

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [32]:
df[df['y']>100]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
6,24,128.76,al,r,e,f,d,f,h,s,...,0,0,0,0,0,0,0,0,0,0
8,27,108.67,w,s,as,e,d,f,i,h,...,1,0,0,0,0,0,0,0,0,0
9,30,126.99,j,b,aq,c,d,f,a,e,...,0,0,1,0,0,0,0,0,0,0
10,31,102.09,h,r,r,f,d,f,h,p,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4202,8402,123.34,ap,l,s,c,d,aa,d,r,...,0,0,0,0,0,0,0,0,0,0
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [38]:
from io import StringIO,BytesIO

In [40]:
data = ('col1,col2,col3\n' # create csv file
        'x,y,1\n'
        'a,b,2\n'
        'c,d,3')

In [41]:
type(data)

str

In [42]:
StringIO()

In [43]:
pd.read_csv(StringIO(data)) # this is to see that how the csv file is created by str

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [46]:
df = pd.read_csv(StringIO(data),usecols=['col1','col2'])
df

  col1 col2
0    x    y
1    a    b
2    c    d

In [48]:
df.to_csv('Table2.csv')

In [53]:
data = ('a,b,c,d\n'
        '1,2,3,4\n'
        '5,6,7,8\n'
        '9,10,11,12\n')
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11,12

In [54]:
df = pd.read_csv(StringIO(data),dtype=int)
df

   a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [56]:
df['a']

0    1
1    5
2    9
Name: a, dtype: int64

In [62]:
df = pd.read_csv(StringIO(data),dtype={'a':int,'b':float,'c':float,'d':int})
df

   a     b     c   d
0  1   2.0   3.0   4
1  5   6.0   7.0   8
2  9  10.0  11.0  12

In [63]:
df.dtypes

a      int64
b    float64
c    float64
d      int64
dtype: object

In [68]:
data = ('index,a,b,c,d\n'
        '0,1,2,3,4\n'
        '1,5,6,7,8\n'
        '2,9,10,11,12\n')
df = pd.read_csv(StringIO(data),index_col=0)
df

       a   b   c   d
index
0      1   2   3   4
1      5   6   7   8
2      9  10  11  12

In [69]:
pd.read_csv(StringIO(data))

   index  a   b   c   d
0      0  1   2   3   4
1      1  5   6   7   8
2      2  9  10  11  12

In [71]:
df = pd.read_csv(StringIO(data),index_col=False)
df

   index  a   b   c   d
0      0  1   2   3   4
1      1  5   6   7   8
2      2  9  10  11  12

In [72]:
df = pd.read_csv(StringIO(data),usecols=['b','c'],index_col=False)
df

    b   c
0   2   3
1   6   7
2  10  11

In [76]:
data = 'a,b\nhello,"bob","nice to see you",5'
pd.read_csv(StringIO(data),escapechar = '\\')

                         a  b
hello bob  nice to see you  5

In [80]:
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv', sep='\t')
df

    sepal_length,sepal_width,petal_length,petal_width,species
0                               5.1,3.5,1.4,0.2,setosa
1                               4.9,3.0,1.4,0.2,setosa
2                               4.7,3.2,1.3,0.2,setosa
3                               4.6,3.1,1.5,0.2,setosa
4                               5.0,3.6,1.4,0.2,setosa
..                                                 ...
145                          6.7,3.0,5.2,2.3,virginica
146                          6.3,2.5,5.0,1.9,virginica
147                          6.5,3.0,5.2,2.0,virginica
148                          6.2,3.4,5.4,2.3,virginica
149                          5.9,3.0,5.1,1.8,virginica

[150 rows x 1 columns]

In [81]:
Data='{"employee_name":"james","email":"james@gmail.com","job_profile":[{"title1":"team lead","title2":"Sr.Developer"}]}'

df= pd.read_json(StringIO(Data)) # this reads the json data and converted into dataframe
df

,employee_name,email,job_profile
0,james,james@gmail.com,"{'title1': 'team lead', 'title2': 'Sr.Developer'}"

In [82]:
df = pd.read_json('https://jsonplaceholder.typicode.com/users')
df

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

In [83]:
df.to_csv('j.csv')

In [85]:
df.to_json()

'{"id":{"0":1,"1":2,"2":3,"3":4,"4":5,"5":6,"6":7,"7":8,"8":9,"9":10},"name":{"0":"Leanne Graham","1":"Ervin Howell","2":"Clementine Bauch","3":"Patricia Lebsack","4":"Chelsey Dietrich","5":"Mrs. Dennis Schulist","6":"Kurtis Weissnat","7":"Nicholas Runolfsdottir V","8":"Glenna Reichert","9":"Clementina DuBuque"},"username":{"0":"Bret","1":"Antonette","2":"Samantha","3":"Karianne","4":"Kamren","5":"Leopoldo_Corkery","6":"Elwyn.Skiles","7":"Maxime_Nienow","8":"Delphine","9":"Moriah.Stanton"},"email":{"0":"Sincere@april.biz","1":"Shanna@melissa.tv","2":"Nathan@yesenia.net","3":"Julianne.OConner@kory.org","4":"Lucio_Hettinger@annie.ca","5":"Karley_Dach@jasper.info","6":"Telly.Hoeger@billy.biz","7":"Sherwood@rosamond.me","8":"Chaim_McDermott@dana.io","9":"Rey.Padberg@karina.biz"},"address":{"0":{"street":"Kulas Light","suite":"Apt. 556","city":"Gwenborough","zipcode":"92998-3874","geo":{"lat":"-37.3159","lng":"81.1496"}},"1":{"street":"Victor Plains","suite":"Suite 879","city":"Wisokyburgh","zipcode":"90566-7771","geo":{"lat":"-43.9509","lng":"-34.4618"}},"2":{"street":"Douglas Extension","suite":"Suite 847","city":"McKenziehaven","zipcode":"59590-4157","geo":{"lat":"-68.6102","lng":"-47.0653"}},"3":{"street":"Hoeger Mall","suite":"Apt. 692","city":"South Elvis","zipcode":"53919-4257","geo":{"lat":"29.4572","lng":"-164.2990"}},"4":{"street":"Skiles Walks","suite":"Suite 351","city":"Roscoeview","zipcode":"33263","geo":{"lat":"-31.8129","lng":"62.5342"}},"5":{"street":"Norberto Crossing","suite":"Apt. 950","city":"South Christy","zipcode":"23505-1337","geo":{"lat":"-71.4197","lng":"71.7478"}},"6":{"street":"Rex Trail","suite":"Suite 280","city":"Howemouth","zipcode":"58804-1099","geo":{"lat":"24.8918","lng":"21.8984"}},"7":{"street":"Ellsworth Summit","suite":"Suite 729","city":"Aliyaview","zipcode":"45169","geo":{"lat":"-14.3990","lng":"-120.7677"}},"8":{"street":"Dayna Park","suite":"Suite 449","city":"Bartholomebury","zipcode":"76495-3109","geo":{"lat":"24.6463","lng":"-168.8889"}},"9":{"street":"Kattie Turnpike","suite":"Suite 198","city":"Lebsackbury","zipcode":"31428-2261","geo":{"lat":"-38.2386","lng":"57.2232"}}},"phone":{"0":"1-770-736-8031 x56442","1":"010-692-6593 x09125","2":"1-463-123-4447","3":"493-170-9623 x156","4":"(254)954-1289","5":"1-477-935-8478 x6430","6":"210.067.6132","7":"586.493.6943 x140","8":"(775)976-6794 x41206","9":"024-648-3804"},"website":{"0":"hildegard.org","1":"anastasia.net","2":"ramiro.info","3":"kale.biz","4":"demarco.info","5":"ola.org","6":"elvis.io","7":"jacynthe.com","8":"conrad.com","9":"ambrose.net"},"company":{"0":{"name":"Romaguera-Crona","catchPhrase":"Multi-layered client-server neural-net","bs":"harness real-time e-markets"},"1":{"name":"Deckow-Crist","catchPhrase":"Proactive didactic contingency","bs":"synergize scalable supply-chains"},"2":{"name":"Romaguera-Jacobson","catchPhrase":"Face to face bifurcated interface","bs":"e-enable strategic applications"},"3":{"name":"Robel-Corkery","catchPhrase":"Multi-tiered zero tolerance productivity","bs":"transition cutting-edge web services"},"4":{"name":"Keebler LLC","catchPhrase":"User-centric fault-tolerant solution","bs":"revolutionize end-to-end systems"},"5":{"name":"Considine-Lockman","catchPhrase":"Synchronised bottom-line interface","bs":"e-enable innovative applications"},"6":{"name":"Johns Group","catchPhrase":"Configurable multimedia task-force","bs":"generate enterprise e-tailers"},"7":{"name":"Abernathy Group","catchPhrase":"Implemented secondary concept","bs":"e-enable extensible e-tailers"},"8":{"name":"Yost and Sons","catchPhrase":"Switchable contextually-based project","bs":"aggregate real-time technologies"},"9":{"name":"Hoeger LLC","catchPhrase":"Centralized empowering task-force","bs":"target end-to-end models"}}}'

In [86]:
df.to_json(orient = 'records')

'[{"id":1,"name":"Leanne Graham","username":"Bret","email":"Sincere@april.biz","address":{"street":"Kulas Light","suite":"Apt. 556","city":"Gwenborough","zipcode":"92998-3874","geo":{"lat":"-37.3159","lng":"81.1496"}},"phone":"1-770-736-8031 x56442","website":"hildegard.org","company":{"name":"Romaguera-Crona","catchPhrase":"Multi-layered client-server neural-net","bs":"harness real-time e-markets"}},{"id":2,"name":"Ervin Howell","username":"Antonette","email":"Shanna@melissa.tv","address":{"street":"Victor Plains","suite":"Suite 879","city":"Wisokyburgh","zipcode":"90566-7771","geo":{"lat":"-43.9509","lng":"-34.4618"}},"phone":"010-692-6593 x09125","website":"anastasia.net","company":{"name":"Deckow-Crist","catchPhrase":"Proactive didactic contingency","bs":"synergize scalable supply-chains"}},{"id":3,"name":"Clementine Bauch","username":"Samantha","email":"Nathan@yesenia.net","address":{"street":"Douglas Extension","suite":"Suite 847","city":"McKenziehaven","zipcode":"59590-4157","geo":{"lat":"-68.6102","lng":"-47.0653"}},"phone":"1-463-123-4447","website":"ramiro.info","company":{"name":"Romaguera-Jacobson","catchPhrase":"Face to face bifurcated interface","bs":"e-enable strategic applications"}},{"id":4,"name":"Patricia Lebsack","username":"Karianne","email":"Julianne.OConner@kory.org","address":{"street":"Hoeger Mall","suite":"Apt. 692","city":"South Elvis","zipcode":"53919-4257","geo":{"lat":"29.4572","lng":"-164.2990"}},"phone":"493-170-9623 x156","website":"kale.biz","company":{"name":"Robel-Corkery","catchPhrase":"Multi-tiered zero tolerance productivity","bs":"transition cutting-edge web services"}},{"id":5,"name":"Chelsey Dietrich","username":"Kamren","email":"Lucio_Hettinger@annie.ca","address":{"street":"Skiles Walks","suite":"Suite 351","city":"Roscoeview","zipcode":"33263","geo":{"lat":"-31.8129","lng":"62.5342"}},"phone":"(254)954-1289","website":"demarco.info","company":{"name":"Keebler LLC","catchPhrase":"User-centric fault-tolerant solution","bs":"revolutionize end-to-end systems"}},{"id":6,"name":"Mrs. Dennis Schulist","username":"Leopoldo_Corkery","email":"Karley_Dach@jasper.info","address":{"street":"Norberto Crossing","suite":"Apt. 950","city":"South Christy","zipcode":"23505-1337","geo":{"lat":"-71.4197","lng":"71.7478"}},"phone":"1-477-935-8478 x6430","website":"ola.org","company":{"name":"Considine-Lockman","catchPhrase":"Synchronised bottom-line interface","bs":"e-enable innovative applications"}},{"id":7,"name":"Kurtis Weissnat","username":"Elwyn.Skiles","email":"Telly.Hoeger@billy.biz","address":{"street":"Rex Trail","suite":"Suite 280","city":"Howemouth","zipcode":"58804-1099","geo":{"lat":"24.8918","lng":"21.8984"}},"phone":"210.067.6132","website":"elvis.io","company":{"name":"Johns Group","catchPhrase":"Configurable multimedia task-force","bs":"generate enterprise e-tailers"}},{"id":8,"name":"Nicholas Runolfsdottir V","username":"Maxime_Nienow","email":"Sherwood@rosamond.me","address":{"street":"Ellsworth Summit","suite":"Suite 729","city":"Aliyaview","zipcode":"45169","geo":{"lat":"-14.3990","lng":"-120.7677"}},"phone":"586.493.6943 x140","website":"jacynthe.com","company":{"name":"Abernathy Group","catchPhrase":"Implemented secondary concept","bs":"e-enable extensible e-tailers"}},{"id":9,"name":"Glenna Reichert","username":"Delphine","email":"Chaim_McDermott@dana.io","address":{"street":"Dayna Park","suite":"Suite 449","city":"Bartholomebury","zipcode":"76495-3109","geo":{"lat":"24.6463","lng":"-168.8889"}},"phone":"(775)976-6794 x41206","website":"conrad.com","company":{"name":"Yost and Sons","catchPhrase":"Switchable contextually-based project","bs":"aggregate real-time technologies"}},{"id":10,"name":"Clementina DuBuque","username":"Moriah.Stanton","email":"Rey.Padberg@karina.biz","address":{"street":"Kattie Turnpike","suite":"Suite 198","city":"Lebsackbury","zipcode":"31428-2261","geo":{"lat":"-38.2386","lng":"57.2232"}},"phone":"024-648-3804","website":"ambrose.net","company":{"name":"Hoeger LLC","catchPhrase":"Centralized empowering task-force","bs":"target end-to-end models"}}]'

In [90]:
# Reading HTML Content
url = 'https://www.fdic.gov/bank/individual/failed/banklist.html'
dfs = pd.read_html(url)
dfs

[                                            Bank Name                City  \
 0                   Metropolitan Capital Bank & Trust             Chicago
 1                        The Santa Anna National Bank          Santa Anna
 2                                Pulaski Savings Bank             Chicago
 3                  The First National Bank of Lindsay             Lindsay
 4               Republic First Bank dba Republic Bank        Philadelphia
 5                                       Citizens Bank            Sac City
 6                            Heartland Tri-State Bank             Elkhart
 7                                 First Republic Bank       San Francisco
 8                                      Signature Bank            New York
 9                                 Silicon Valley Bank         Santa Clara
 10                                  Almena State Bank              Almena
 11                         First City Bank of Florida   Fort Walton Beach
 12                               The First State Bank       Barboursville
 13                                 Ericson State Bank             Ericson
 14                   City National Bank of New Jersey              Newark
 15                                      Resolute Bank              Maumee
 16                              Louisa Community Bank              Louisa
 17                               The Enloe State Bank              Cooper
 18                Washington Federal Bank for Savings             Chicago
 19    The Farmers and Merchants State Bank of Argonia             Argonia
 20                                Fayette County Bank          Saint Elmo
 21  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 22                                     First NBC Bank         New Orleans
 23                                      Proficio Bank  Cottonwood Heights
 24                      Seaway Bank and Trust Company             Chicago

             State   Cert                Acquiring Institution  \
 0        Illinois  57488              First Independence Bank
 1           Texas   5520            Coleman County State Bank
 2        Illinois  28611                      Millennium Bank
 3        Oklahoma   4134               First Bank & Trust Co.
 4    Pennsylvania  27332    Fulton Bank, National Association
 5            Iowa   8758            Iowa Trust & Savings Bank
 6          Kansas  25851               Dream First Bank, N.A.
 7      California  59017            JPMorgan Chase Bank, N.A.
 8        New York  57053                  Flagstar Bank, N.A.
 9      California  24735  First–Citizens Bank & Trust Company
 10         Kansas  15426                          Equity Bank
 11        Florida  16748            United Fidelity Bank, fsb
 12  West Virginia  14361                       MVB Bank, Inc.
 13       Nebraska  18265           Farmers and Merchants Bank
 14     New Jersey  21111                      Industrial Bank
 15           Ohio  58317                   Buckeye State Bank
 16       Kentucky  58112    Kentucky Farmers Bank Corporation
 17          Texas  10716                   Legend Bank, N. A.
 18       Illinois  30570                   Royal Savings Bank
 19         Kansas  17719                          Conway Bank
 20       Illinois   1802            United Fidelity Bank, fsb
 21      Wisconsin  30003  First-Citizens Bank & Trust Company
 22      Louisiana  58302                         Whitney Bank
 23           Utah  35495                    Cache Valley Bank
 24       Illinois  19328                  State Bank of Texas

          Closing Date  Fund  Sort ascending
 0    January 30, 2026                 10550
 1       June 27, 2025                 10549
 2    January 17, 2025                 10548
 3    October 18, 2024                 10547
 4      April 26, 2024                 10546
 5    November 3, 2023                 10545
 6       July 28, 2023                 10544
 7         May 1, 2023                 10543
 8      March 12, 2023                 10540
 9      March 10, 2023                 10539
 10   October 23, 2020                 10538
 11   October 16, 2020                 10537
 12      April 3, 2020                 10536
 13  February 14, 2020                 10535
 14   November 1, 2019                 10534
 15   October 25, 2019                 10533
 16   October 25, 2019                 10532
 17       May 31, 2019                 10531
 18  December 15, 2017                 10530
 19   October 13, 2017                 10529
 20       May 26, 2017                 10528
 21        May 5, 2017                 10527
 22     April 28, 2017                 10526
 23      March 3, 2017                 10525
 24   January 27, 2017                 10524  ]

In [91]:
dfs[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524

In [93]:
df_excel= pd.read_excel(announcement_hindi.xlsx)
df_excel.head()

NameError: name 'announcement_hindi' is not defined

In [ ]:
df_excel.to_pickle('df_excel')
df = pd.read.pickle('df_excel')
df.head